### ISSUE TITLE
 Settings tab "About"

### ISSUE THREAD

**Issue by annamaksimik** [easably/platform-player-extension#101]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/EasyLang_Player?node-id=1%3A2

![image](https://user-images.githubusercontent.com/58423687/81201439-f170f180-8fcd-11ea-8310-2792e6cab679.png)

Сделай белую линию ярче(как в скетче)
![image](https://user-images.githubusercontent.com/58423687/81201578-19f8eb80-8fce-11ea-949e-35324150d2d0.png)

**Comment by sergeifedorenko** [comment]
@Vlad-CSA add source code for the button "Contact Us", please

**Comment by pavladan** [comment]
Is it ok ?
![image](https://user-images.githubusercontent.com/44526604/81261210-52d3a780-9044-11ea-8d91-cd338320ab89.png)

**Comment by sergeifedorenko** [comment]
@pavladan for me need to cut areas where red circles and add margins
@annamaksimik what do you think?
![image](https://user-images.githubusercontent.com/5947223/81261842-76e3b880-9045-11ea-8039-ae7757b7d266.png)

**Comment by annamaksimik** [comment]
margins in file Figma


![image](https://user-images.githubusercontent.com/58423687/81265596-08562900-904c-11ea-856d-692c252b917a.png)

**Comment by sergeifedorenko** [comment]
@annamaksimik can we add inner paging? :)
![image](https://user-images.githubusercontent.com/5947223/81287015-b53f9e80-906a-11ea-95c2-8a6a20addb11.png)

**Comment by annamaksimik** [comment]
неуверенна что стоит так делать, так как все вкладки Settings с одинаковыми отступами

![image](https://user-images.githubusercontent.com/58423687/81287540-9e4d7c00-906b-11ea-95f7-7b1faaf4c781.png)

**Comment by sergeifedorenko** [comment]
Ok, up to you!

**Comment by pavladan** [comment]
Is it ok?
![image](https://user-images.githubusercontent.com/44526604/81329321-09687400-90a7-11ea-8210-5497b8bc30c5.png)
