### ISSUE TITLE
Unstable behavior for ToolTip with selected text

### ISSUE THREAD

**Issue by sergeifedorenko** [easably/platform-player-extension#102]
Unstable behavior for ToolTip with selected text

1. Select a text in English subtitles 
2. Hold the cursor under selected text (2-5 sec)
3. Go out from the position where was selected cursor
4. The ToolTip did not appear

and can be vice versa situation (see screenshot)
You can have no one selected text and see the ToolTip

**Expected behavior**
The ToolTip should be always

![image](https://user-images.githubusercontent.com/5947223/81213416-fbe7b700-8fde-11ea-8c5a-52b3fda5a7b7.png)

**Desktop (please replace with your actual data):**
 - Version [82]

**Comment by pavladan** [comment]
This bug is not reproduced depending on the retention time. This bug is reproduced when, when you release the highlight key, the cursor goes beyond the borders of the highlighted block

**Comment by pavladan** [comment]
@sergeifedorenko , If you increase the response zone, unwanted characters (invisible characters, unselected elements, words from other blocks) may fall into the translation.

![image](https://user-images.githubusercontent.com/44526604/81256460-4007a580-9039-11ea-91f8-9aa5b85f34d3.png)
For example, in the image, complete the selection with a red cross and in the translation, you will receive unselected characters “RU

**Comment by pavladan** [comment]
I changed the selection logic, the selection area has become a little larger. But the menu will not drop out if the selection fell on someone else's symbol, although the user does not see it. Commit 29f12549e31e70f37b3b0bdd8dedb367ed45e9f6
