### ISSUE TITLE
Highlighting words under the cursor

### ISSUE THREAD

**Issue by sergeifedorenko** [easably/platform-player-extension#104]
We need to highlight words in the section (English) with a foreign text. When the user clicks on the word we need to show a service window with the translation.

![image](https://user-images.githubusercontent.com/5947223/81258572-a0e5ac80-903e-11ea-9de0-50649f785e80.png)

**Comment by pavladan** [comment]
Done in 3790c62560bcbe2c86526215cbed37dcddf25111
