### ISSUE TITLE
Add link “ instructions” in the frame for downloading video 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#106]
![73C79997-7430-4CA5-B034-FD5D7AEF4D73](https://user-images.githubusercontent.com/63041847/81301649-fee7b380-9081-11ea-9c43-c33c2788ec8e.jpeg)

Or if it doesn’t work out add link “instructions in browser”
![452AD814-411B-4255-ADB7-9C0F15AD7190](https://user-images.githubusercontent.com/63041847/81301832-40785e80-9082-11ea-940f-7468a2091a68.jpeg)

@pavladan

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/81303046-dcef3080-9083-11ea-893d-5cfd39e547a8.png)
 or 
![image](https://user-images.githubusercontent.com/58423687/81303074-e7112f00-9083-11ea-881a-34bea624aec7.png)
