### ISSUE TITLE
Add required icons “sign in” and “ welcome”

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#110]
Add an icon with 2 steps: “sign in” and “welcome” .
But under the second step remove : “ don’t show again” and “close”
![A9AAF037-8EB3-4AD1-9137-A9E51F5CE0D5](https://user-images.githubusercontent.com/63041847/81666343-95cdba80-944a-11ea-9123-a5aa82469f56.png)

**Comment by pavladan** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=225%3A63
