### ISSUE TITLE
the button "save" is non-working

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#115]
![player](https://user-images.githubusercontent.com/63041847/81929919-7c667300-95f0-11ea-9978-d2bf0c3a8a1c.jpg)
![player1](https://user-images.githubusercontent.com/63041847/81929933-812b2700-95f0-11ea-9b31-94d973f73c2d.jpg)
 if a user want to change anything in the settings he can do it without tapping on "save"
![player2](https://user-images.githubusercontent.com/63041847/81930281-0adaf480-95f1-11ea-8c34-d601c07fa4b3.jpg)

 - OS: [Win 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by pavladan** [comment]
Fixed in 2867d075a64d0e0a6de4e51a8a79095321e75e7a
