### ISSUE TITLE
[4h-8h]Correct instruction in youtube

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#130]
@annamaksimik  help with the design of:
show checkbox when a user coppied a video from youtube

**Comment by KatyaLogosh** [comment]
> https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1068%3A55
> 
> ![image](https://user-images.githubusercontent.com/58423687/84038705-ed5b3980-a9a8-11ea-8414-cb8e8f3b2231.png)

@annamaksimik can you help with the design of instruction: the problem of all users is that they don't understand that the 1 step is connected with the second step, and they don't understand which video they should download .

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1271%3A27

![image](https://user-images.githubusercontent.com/58423687/84996340-cb567980-b155-11ea-868d-055801e45bc6.png)

**Comment by sergeifedorenko** [comment]
https://easylang.app/static-html/instructionYoutube.html 
1) - need delete
![image](https://user-images.githubusercontent.com/5947223/85288317-2feb3e80-b49e-11ea-854e-239630a01dac.png)

2) current state in player
![image](https://user-images.githubusercontent.com/5947223/85288439-6628be00-b49e-11ea-8c6b-f697b4fafc97.png)

**Comment by Alexx-13** [comment]
Accourding to Issue #130, new conditions were met. https://easylang.app/static-html/instructionYoutube.html

**Comment by Alexx-13** [comment]
https://easylang.app/instruction-youtube-desctop - link to check the task.

**Comment by Alexx-13** [comment]
Need to take new url as link for iframe (/instruction-youtube-desctop/)

**Comment by KatyaLogosh** [comment]
- [ ] the second step is missed :
![image](https://user-images.githubusercontent.com/63041847/85379286-477d0280-b544-11ea-95d4-91e3649f8513.png)
- [ ] Add "Url copied" to the first step

**Comment by bagorbenko** [comment]
I am closing this issue because the YouTube player has been modified. The instruction is not relevant.
