### ISSUE TITLE
[2h]redesign current hiding eye.

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#136]
Users don't understand its destination
![4](https://user-images.githubusercontent.com/63041847/82670722-596a3d80-9c46-11ea-89ef-1ca8bf5c0430.jpg)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/IKc3yczU3iBtfhFykYyf66/Extension?node-id=181%3A414

![image](https://user-images.githubusercontent.com/58423687/85145895-ead4cb80-b255-11ea-8b25-711f16a245d5.png)

**Comment by KatyaLogosh** [comment]
There is an old version of hiding eye 
![image](https://user-images.githubusercontent.com/63041847/85841244-7c888f80-b7a6-11ea-8683-7670b61876ae.png)

![image](https://user-images.githubusercontent.com/63041847/85841075-3c291180-b7a6-11ea-9fce-bad9889e6807.png)

**Comment by KatyaLogosh** [comment]
@6alex6kash6 send please pull request to @pavladan
