### ISSUE TITLE
video (18+minutes) doesn't sorted

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#138]
![1 ihj](https://user-images.githubusercontent.com/63041847/84167826-5f9e4d80-aa7f-11ea-90e6-dd03d09520da.png)
![2 3s3](https://user-images.githubusercontent.com/63041847/84167842-63ca6b00-aa7f-11ea-8c95-53523ce520cb.png)

**Comment by pavladan** [comment]
Fixed in 12b3e2afa6c3aa32887da54cf127d8ad7252d43c
