### ISSUE TITLE
[1h] New design for "history" and "instruction" buttons 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#146]
![image](https://user-images.githubusercontent.com/63041847/84266711-9b8fec00-ab2d-11ea-8d7f-4fdbed89595c.png)
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=225%3A64

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1099%3A1275

![image](https://user-images.githubusercontent.com/58423687/84604127-818f3a00-ae9c-11ea-9599-4318dd1cac29.png)

**Comment by KatyaLogosh** [comment]
> https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1099%3A1275
> 
> ![image](https://user-images.githubusercontent.com/58423687/84604127-818f3a00-ae9c-11ea-9599-4318dd1cac29.png)

can you name just "Instruction" without "in browser"

**Comment by sergeifedorenko** [comment]
![image](https://user-images.githubusercontent.com/5947223/84766339-52321780-afd9-11ea-9319-7a73cd8764f7.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/84766992-632f5880-afda-11ea-9716-db5e6819fa28.png)
