### ISSUE TITLE
Video slowdown function

### ISSUE THREAD

**Issue by bagorbenko** [easably/platform-player-extension#147]
- [x] create slowdown button (little turtle, sloth, snail)
@annamaksimik 
![image](https://user-images.githubusercontent.com/63041847/84479448-a36d9e80-ac9b-11ea-9a9b-e6783ab18ee7.png)

- [x] add slowdown function in player 
(0,8x speed video playback)
@pavladan

**Comment by pavladan** [comment]
Made in 200dea6ea6fa5faaa27892427c5255f824a0f500
