### ISSUE TITLE
missing video list in TED. Player.

### ISSUE THREAD

**Issue by bagorbenko** [easably/platform-player-extension#149]
**Missing video list**

1. Go to EasyLang Player / TED
2. Choose Sort by - Newest

**Expected behavior**
Show the newest videos

**Screenshots**
![image](https://user-images.githubusercontent.com/66242439/84356028-4820ab00-abcc-11ea-9a86-d5ca2ff317ab.png)

**Desktop (please replace with your actual data):**
 - OS: Win 10
 - Version: 0.8.88

**Comment by pavladan** [comment]
Fixed in c0d3439d60e056874804ab33e662812265026218
