### ISSUE TITLE
Chooses language pair. Registration. Player

### ISSUE THREAD

**Issue by bagorbenko** [easably/platform-player-extension#157]
**Describe the bug**
Chooses language pair after second user registration on 1 PC.

**To Reproduce**
1. Go to Player, Log Out
2. Sign up new user
3. Window with a language pair is not show

**Expected behavior**
Window with a language pair is show after sign up new user.

**Screenshots**
![image](https://user-images.githubusercontent.com/66242439/84502746-96fc3c80-acc1-11ea-97bf-4ca2d4a5ba9e.png)

**Desktop (please replace with your actual data):**
 - OS: Win 10
 - Version 0.8.88

**Comment by pavladan** [comment]
Fixed in fd20489a70ccda2b21736cf38e417b56dc435635
