### ISSUE TITLE
Moving in the registration window with TAB. Player.

### ISSUE THREAD

**Issue by bagorbenko** [easably/platform-player-extension#159]
**Describe the bug**
Moving in the registration window with TAB

**To Reproduce**
1. Go to Player
2. Write down e-mail
3. Press TAB multiple times

**Expected behavior**
Moving the active window using the TAB only among 4 fields (Mail, password, password replay, user agreement)

**Screenshots**
![image](https://user-images.githubusercontent.com/66242439/84506251-bf873500-acc7-11ea-94c2-225f4d3f8ce5.png)

**Desktop**
 - OS: [Win 10]
 - Version [0.8.88]

**Comment by pavladan** [comment]
Fixed in 08ebd03428a7232e773b5cbd859dbaed6d043641
