### ISSUE TITLE
Change extension functionality during selection.

### ISSUE THREAD

**Issue by bagorbenko** [easably/platform-player-extension#160]
**Change extension functionality during selection.**

Some users complain about a pop-up when trying to copy text.

![image](https://user-images.githubusercontent.com/66242439/84518424-5c060300-acd9-11ea-8806-a58156075e5b.png)

![image](https://user-images.githubusercontent.com/66242439/84518871-0120db80-acda-11ea-8a66-0f14a09d2a2b.png)

**Comment by sergeifedorenko** [comment]
added @annamaksimik for an initial meeting in the office
