### ISSUE TITLE
 make all buttons one style

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#163]
![image](https://user-images.githubusercontent.com/63041847/84640914-01e88600-af03-11ea-962e-e65556acebe0.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1227%3A643

![image](https://user-images.githubusercontent.com/58423687/85008514-c39ed100-b165-11ea-8834-8eaae6e14d3a.png)
