### ISSUE TITLE
remove sorting if no added word

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#165]
if the user has not added any words, sorting remains 
![image](https://user-images.githubusercontent.com/63041847/84643295-517c8100-af06-11ea-91f3-7c43a3c7d08a.png)
![image](https://user-images.githubusercontent.com/63041847/84643350-60633380-af06-11ea-9292-84ac8156c688.png)

**Comment by pavladan** [comment]
Fixed in ffbb0133501b877749078b81df375c5dd28e9edf
