### ISSUE TITLE
redesign icon games

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#167]
- [x] redesign the icon of games to 
![image](https://user-images.githubusercontent.com/63041847/84664900-e04dc580-af27-11ea-941d-dc7ec6797d0c.png)
- [x] Change "word repeat games" to " Go to Tutor"
![image](https://user-images.githubusercontent.com/63041847/84664835-c4e2ba80-af27-11ea-86a0-b5fd47f0dcba.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1176%3A756

![image](https://user-images.githubusercontent.com/58423687/85002878-20968900-b15e-11ea-96a7-a49bf1d867e0.png)

**Comment by annamaksimik** [comment]
**redesign the icon of games to**
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1227%3A643


![image](https://user-images.githubusercontent.com/58423687/85004244-03fb5080-b160-11ea-8912-79df0f216c0d.png)
![image](https://user-images.githubusercontent.com/58423687/85004313-183f4d80-b160-11ea-9755-0388c67aa4ee.png)

**Comment by KatyaLogosh** [comment]
> https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1176%3A756
> 
> ![image](https://user-images.githubusercontent.com/58423687/85002878-20968900-b15e-11ea-96a7-a49bf1d867e0.png)

Can you increase the title " go to tutor"?

**Comment by KatyaLogosh** [comment]
> **redesign the icon of games to**
> https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1227%3A643
> 
> ![image](https://user-images.githubusercontent.com/58423687/85004244-03fb5080-b160-11ea-8912-79df0f216c0d.png)
> ![image](https://user-images.githubusercontent.com/58423687/85008339-88040700-b165-11ea-98db-f0ecb7e8c261.png)
> 
> ![image](https://user-images.githubusercontent.com/58423687/85004313-183f4d80-b160-11ea-9755-0388c67aa4ee.png)

Can you add when user logged in? 
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1227%3A643
