### ISSUE TITLE
the title of the video displays incorrectly

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#172]
after saving the words  from the local video, the tutorial displays an uncomfortable title of the lesson
![image](https://user-images.githubusercontent.com/63041847/84760459-ba303000-afd0-11ea-9b6b-649376a56bb4.png)

**Comment by sergeifedorenko** [comment]
@KatyaLogosh always better to have more correct version of the ticket 

For instance: 

_Path for reproducing_
- Is TED video
- the URL of the TED video
https://www.ted.com/talks/tyler_cowen_be_suspicious_of_simple_stories

_Expected behavior_

- expected title for TED video  
**Be suspicious of simple stories**  or **Tyler Cowen, Be suspicious of simple stories**

**Comment by sergeifedorenko** [comment]
@pavladan @pavladan
I missed that it was the local file

sorry 
I closing it
