### ISSUE TITLE
 increase in size tooltips 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#180]
tooltips in the player are unreadable

![image](https://user-images.githubusercontent.com/63041847/85014347-c3ef9a00-b16e-11ea-913e-88a310a9e070.png)

**Comment by annamaksimik** [comment]
Tooltips(svg , png) - [Player.zip](https://github.com/easably/platform-player-extension/files/4799102/Player.zip)
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1291%3A964

![image](https://user-images.githubusercontent.com/58423687/85031372-4421f980-b187-11ea-9bea-0d73a8ff7a0c.png)
