### ISSUE TITLE
[4h] 4 buttons: TED, Youtube, Netflix, Local Files. 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#183]
make the frame " click or drag..." smaller and insert extension advertising
Example:
![image](https://user-images.githubusercontent.com/63041847/83736320-22d6ee80-a65a-11ea-8c3e-355c537d3e12.png)
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1099%3A1275

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1291%3A1823

![image](https://user-images.githubusercontent.com/58423687/85038185-f7422100-b18e-11ea-9528-e395ec65ba9c.png)

**Comment by bagorbenko** [comment]
supporting mkv

**Comment by KatyaLogosh** [comment]
> https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1291%3A1823
> 
> ![image](https://user-images.githubusercontent.com/58423687/85038185-f7422100-b18e-11ea-9528-e395ec65ba9c.png)

Can you make modern design? And make "Ted" the first @annamaksimik

**Comment by KatyaLogosh** [comment]
> supporting mkv

Local files storage 
Supporting MKV

**Comment by bagorbenko** [comment]
Adaptive buttons
