### ISSUE TITLE
Redesign home screen 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#184]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1291%3A1823
Local files storage
Supporting MKV
Can you make modern design? And make "Ted" the first

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1291%3A1823

![image](https://user-images.githubusercontent.com/58423687/85113598-35d3ec00-b220-11ea-8529-725a1c9b2c96.png)

**Comment by sergeifedorenko** [comment]
@annamaksimik 
1) Change title - Open Local Files 
2) mkv link https://www.quora.com/Is-there-any-free-software-which-I-can-use-to-convert-mkv-file-to-mp3-audio-file

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1291%3A1823

![image](https://user-images.githubusercontent.com/58423687/85140798-74809b00-b24e-11ea-9d83-666ea84c49a8.png)
