### ISSUE TITLE
[1.5h]Align signup/signin window 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#197]
Raise the brain, that everything will be aligned 
![image](https://user-images.githubusercontent.com/63041847/85389198-c88dc700-b54f-11ea-8ff8-6c88c910a8e1.png)

https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1398%3A4922

**Comment by bagorbenko** [comment]
How high should he drag it? Please, use Figma to correctly show the location of the mascot.
@KatyaLogosh
