### ISSUE TITLE
make design of Youtube screen

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#200]
![cdnByDe47WM](https://user-images.githubusercontent.com/63041847/85408731-92f7d680-b56d-11ea-9b84-c5bc5e4500eb.jpg)
![YeZI2CTTc1g](https://user-images.githubusercontent.com/63041847/85408739-94c19a00-b56d-11ea-9f4b-e4da2be6fcb1.jpg)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1416%3A3006

![image](https://user-images.githubusercontent.com/58423687/85513664-e74d9580-b603-11ea-9527-601e7fa1fae6.png)
![image](https://user-images.githubusercontent.com/58423687/85513684-ed437680-b603-11ea-8363-8435474ff39f.png)

**Comment by sergeifedorenko** [comment]
@annamaksimik @KatyaLogosh We need the functionality for YouTube page where the user can understand.

"A YouTube link already in the buffer!"

**Comment by sergeifedorenko** [comment]
@annamaksimik related https://github.com/easably/platform-player-extension/issues/130

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1416%3A3082
![image](https://user-images.githubusercontent.com/58423687/85557720-b5065d00-b630-11ea-81e0-8aa05ab1b5d8.png)
