### ISSUE TITLE
[5h-10h]Implement youtube screen 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#203]
- [x] There should be 16 videos from different channels. @bagorbenko will help us with them 
- [x]  there should be static pictures, which are placed on video.
- [x] Url- we put video on url bar, then we tap on downloading video, than video displays 
![cdnByDe47WM](https://user-images.githubusercontent.com/63041847/85409619-b2dbca00-b56e-11ea-9c2a-b54243def3a6.jpg)
![YeZI2CTTc1g](https://user-images.githubusercontent.com/63041847/85409624-b40cf700-b56e-11ea-9103-0d679f595359.jpg)

**Comment by sergeifedorenko** [comment]
@Alexx-13  https://www.youtube.com/results?search_query=learn+english&sp=EgIoAQ%253D%253D
![image](https://user-images.githubusercontent.com/5947223/85529490-c55d0e80-b615-11ea-863b-75890e578319.png)

**Comment by annamaksimik** [comment]
#200  make design of Youtube screen

**Comment by KatyaLogosh** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1416%3A3082
@Alexx-13 there is a link

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1416%3A3082

![image](https://user-images.githubusercontent.com/58423687/85740490-56adad00-b70a-11ea-9a8c-42903faf50d4.png)

**Comment by Alexx-13** [comment]
https://github.com/easably/platform-player-extension/tree/player-youtube-issue-203 - branch with code

**Comment by 6alex6kash6** [comment]
@KatyaLogosh close the task cause its not actual
