### ISSUE TITLE
Change the design of subtitles on the video.

### ISSUE THREAD

**Issue by bagorbenko** [easably/platform-player-extension#206]
**Describe the bug**
Display of subtitles on the video.

**To Reproduce**
1. Go to Player - Youtube
2. Add video
3. Change sub position in settings

**Expected behavior**
Change design the display of subtitles on the video.

**Screenshots**
![image](https://user-images.githubusercontent.com/66242439/85431155-cfd1c680-b589-11ea-965d-97eb55fc8c5d.png)

**Desktop:**
 - OS: [Win 10]
 - Version [0.8.13]

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1424%3A474
![image](https://user-images.githubusercontent.com/58423687/85526489-b9bc1880-b612-11ea-8e3d-b21697de9219.png)

**Analogs**

![image](https://user-images.githubusercontent.com/58423687/85526671-deb08b80-b612-11ea-9c83-ecbec62f3fb6.png)
![image](https://user-images.githubusercontent.com/58423687/85526731-eb34e400-b612-11ea-911d-80dd56dcc4c1.png)
![image](https://user-images.githubusercontent.com/58423687/85526795-f9830000-b612-11ea-809d-fcbcbd62d654.png)

**Comment by KatyaLogosh** [comment]
@pavladan we chosen the first one 
![image](https://user-images.githubusercontent.com/63041847/85527981-0e13c800-b614-11ea-83db-cc68856ff8d8.png)
