### ISSUE TITLE
set A/B test for new youTube page

### ISSUE THREAD

**Issue by lllana** [easably/platform-player-extension#207]
**To check UX solution on a number of pics on the YouTube page** 

**Describe the solution you'd like**
Run AB tests of 2 versions in [Google Optimize ](https://optimize.google.com/optimize/home/) to see the difference in engagement and if there is any link to customer conversion 

**Describe alternatives you've considered**
Wait to see bounce rate (not effective), 
[Goggle analytics no longer allows creating AB test in Goggle Analytics](https://support.google.com/analytics/answer/9366791) we should use [Google Optimize ](https://optimize.google.com/optimize/home/)

**Additional context**
Objectives
- [x] check the settings for [Google Optimize ](https://optimize.google.com/optimize/home/)
- [ ] describe technical requirements to set AB tests
- [ ] make AB versions of YouTube pages
- [ ] set analytics of the events on A and B YouTube pages

**Comment by AbeYelemessov** [comment]
[Current Google Optimize settings](https://optimize.google.com/optimize/home/#/accounts/4703329670/containers/13915438/experiments/6)
Requirements(@Alexx-13 ):
- [ ] Inserting Code Snippet into website code: 
<script src="https://www.googleoptimize.com/optimize.js?id=OPT-PQPT2Z9"></script>
- [ ] [Add Google Analytics events](https://docs.google.com/spreadsheets/d/18p4NWxepXpZBWQP7maThPgJXkVyVBzNWSEaVumRdRkE/edit?usp=sharing)

**Comment by lllana** [comment]
The problem solved with a change in YouTube section realization
