### ISSUE TITLE
in the youtube advertisement links after watching video are unavailable

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#213]
- [ ] Description:
After watching video from youtube advertisement links are unavailable 

1. Go to youtube 
2. Copy video (https://www.youtube.com/watch?v=h6Ol3eprKiw)
3. Insert the link to the player 
4. watch the till the end.
5. the video advertisement are unavailable 
expected behavior:

The links are clickable, or if its impossible- remove them

Screenshots
![image](https://user-images.githubusercontent.com/63041847/85827275-a5048f80-b78e-11ea-8791-f7333b551443.png)

Another bug:

- [ ] 

Description:
When a user want to insert English song link from youtube (https://www.youtube.com/watch?v=MwpMEbgC7DA) in the player - the video is unavailable .

1. Go to player
2. Click on youtube
3. Copy a video from youtube (https://www.youtube.com/watch?v=MwpMEbgC7DA)
4. Insert song link from youtube to the player
5. the video is unavailable
Expected behavior
Songs and clips will be displayed

Screenshots
https://user-images.githubusercontent.com/63041847/85525466-ca1fc380-b611-11ea-84a6-9173ea45ce8e.png

**Comment by pavladan** [comment]
@KatyaLogosh this is not real with this YouTube play method :(

**Comment by KatyaLogosh** [comment]
> @KatyaLogosh this is not real with this YouTube play method :(

So i should close the task? or remove it from "Approved"?
