### ISSUE TITLE
[30min]Redesign snail in tooltip

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#220]
![image](https://user-images.githubusercontent.com/63041847/85990284-7559bf80-b9fa-11ea-8afa-b82e18c283c7.png)
![image](https://user-images.githubusercontent.com/63041847/85991768-91f6f700-b9fc-11ea-9689-7f28f8b2989c.png)

the snail in the player is not bright and the user may not notice it

Note: Make the buttons Repeat and Repeat slow brighter

**Comment by annamaksimik** [comment]
**Button  "Slow Repeat"**
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1494%3A44

![image](https://user-images.githubusercontent.com/58423687/86015402-304d8180-ba2a-11ea-9552-e98a1bb57f4d.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1494%3A69

![image](https://user-images.githubusercontent.com/58423687/86020477-a48b2380-ba30-11ea-84c3-2a5e4cdddd98.png)

**Comment by KatyaLogosh** [comment]
@6alex6kash6 you are to remove snail from the tooltip 
![image](https://user-images.githubusercontent.com/63041847/86220857-d9ac8880-bb8c-11ea-82f6-734b293ad840.png)
