### ISSUE TITLE
add 16 pictures window to the youtube

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#230]
Description:
Add link " recommedations" to the youtube.
This link leads users to the 16 pictures page :
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1416%3A3082
https://github.com/easably/platform-player-extension/tree/player-youtube-issue-203 - branch with code
![image_2020_06_29T14_25_43_721Z](https://user-images.githubusercontent.com/63041847/86122292-40279d00-bae0-11ea-9341-ca1059a42fbe.png)

**Comment by lllana** [comment]
- [ ] @lllana to add events to GA

**Comment by bagorbenko** [comment]
@6alex6kash6 Translate the quantity of followers from russian to english (mln followers)
![image](https://user-images.githubusercontent.com/66242439/86255633-03cb6e00-bbc0-11ea-953a-7a2f9bc9b014.png)
