### ISSUE TITLE
The label "easylang" appears several times

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#237]
Description:
When a user highlight the word in the article- the label appears severl times :
![image](https://user-images.githubusercontent.com/63041847/86248818-10979400-bbb7-11ea-86c1-4fee70b596d0.png)
![image](https://user-images.githubusercontent.com/63041847/86248763-fcec2d80-bbb6-11ea-86d1-13e5ed4f366f.png)

 - OS: [Win 10]
 - Browser [Google Chrome]

**Comment by bagorbenko** [comment]
Use the old version of the extension.
