### ISSUE TITLE
[Extension] Extension is cut on the amazon

### ISSUE THREAD

**Issue by lizakostyushkina** [easably/platform-player-extension#43]
![image](https://user-images.githubusercontent.com/58728395/71349968-452ff080-2581-11ea-841c-bf0518da360a.png)

**Comment by sini4ka08** [comment]
Now the extension does not see the text of the product description at all.
URL - https://www.amazon.com/Graphic-Design-Things-Explain-Better/dp/0062413902/ref=sr_1_3?keywords=director+Tibor+Kalman&qid=1582195757&sr=8-3

**Additional Info:**
Google translator 2.0.8 extension also does not see. But eJOY English - Word Master 3.5.5 sees, but also cuts off.
![Amazon1](https://user-images.githubusercontent.com/52330389/74929260-2ff20980-53ec-11ea-9e99-6425ec19e9b9.png)

**Comment by pavladan** [comment]
In the [0.8.66](https://github.com/easably/platform-player-extension/releases/tag/0.8.66) version the bug did not play
