### ISSUE TITLE
[Extension & Player] Inactive button (Add to my lesson) doesn't make sense when translating a sentence

### ISSUE THREAD

**Issue by sini4ka08** [easably/platform-player-extension#67]
**Describe the bug**
An inactive button [Add to my lesson] doesn't make sense, because this link is always inactive when translating a sentence.

**Screenshots**
For player - 
![Translate sentence](https://user-images.githubusercontent.com/52330389/76290501-5bb23200-62bc-11ea-8bd5-b71ff353148a.png)
For article - 
![Translate sentence1](https://user-images.githubusercontent.com/52330389/76290505-5d7bf580-62bc-11ea-815b-fa139ca41b1b.png)

**Desktop:**
- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.132]

**Comment by pavladan** [comment]
Fixed in [0.8.66](https://github.com/easably/platform-player-extension/releases/tag/0.8.66) version
