### ISSUE TITLE
[Extension] When the extension is installed, our RoadMap breaks in github Projects

### ISSUE THREAD

**Issue by sini4ka08** [easably/platform-player-extension#69]
**Describe the bug**
When the extension is installed, our RoadMap breaks in github Projects.

**Screenshots**
![RoadMap in git](https://user-images.githubusercontent.com/52330389/76315045-ff193c00-62e8-11ea-9ba7-81bce15d134d.png)

**Desktop:**
- OS: [Windows 8 & 10]
- Browser [Google Chrome]
- Version [80.0.3987.132]

**Comment by pavladan** [comment]
Fixed in [0.8.66](https://github.com/easably/platform-player-extension/releases/tag/0.8.66) version
