### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by pavladan** [easably/platform-player-extension#70]
You need to rename this repository because it contains both the extension and the player (continuation of [this](https://github.com/easably/player) project)

**Comment by pavladan** [comment]
Example: **Learning Content Collector**

**Comment by sergeifedorenko** [comment]
@pavladan Check it please platform-player-extension

**Comment by pavladan** [comment]
I would like a more general name, not based on the platform

**Comment by pavladan** [comment]
Ok.
