### ISSUE TITLE
[Player] Updated player doesn't open on desktop.

### ISSUE THREAD

**Issue by sini4ka08** [easably/platform-player-extension#72]
**Describe the bug**
Updated player that you dropped on skype 12.03.20 at 17:42.

**Screenshots**
![Updated player doesn't open](https://user-images.githubusercontent.com/52330389/76606424-4723a300-6523-11ea-9893-adffa2b97c07.png)/

**Desktop:**
- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.132]

**Comment by pavladan** [comment]
Fixed in 64de2eb2837ef6efcdeb2f92c748fa93dde042fa
