### ISSUE TITLE
[Player] The mark icon and the search box break and look huge on some computers

### ISSUE THREAD

**Issue by sini4ka08** [easably/platform-player-extension#73]
**Describe the bug**
 The mark icon and the search box break and look huge on some computers.

**Screenshots**
![mark icon breaks](https://user-images.githubusercontent.com/52330389/76607674-6d4a4280-6525-11ea-8deb-700c99e43908.png)
![mark icon breaks2](https://user-images.githubusercontent.com/52330389/76607677-6e7b6f80-6525-11ea-9ea9-3f3c76603b06.png)

**Desktop:**
 - OS: [Win 10]

**Comment by pavladan** [comment]
Fixed in d4f2759e4ceb62759043ece4220e9894d423e6c2
