### ISSUE TITLE
We need to prevent the result after mouse clicking on "Video zone"

### ISSUE THREAD

**Issue by sergeifedorenko** [easably/platform-player-extension#75]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please replace with your actual data):**
 - OS: [Win 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by pavladan** [comment]
Fixed in 1a818f8f1085982e2f48bbb0fca41a439e292394
