### ISSUE TITLE
[Player] Interaction with tutor

### ISSUE THREAD

**Issue by sini4ka08** [easably/platform-player-extension#86]
- [x] Need to modify or delete the button [Open the original article] in the tutor.
When a user click on the [Open original article], page opens URL - https://easy4learn.com/[Player]%20D:/Movies%20with%20subtitles/Wild.Wild.West.1999.1080p.BluRay.x264.YIFY.mp4
- [x] When a user selects a word with a click, the tutor considers this space a character.
![gap as a char](https://user-images.githubusercontent.com/52330389/75984915-5770c800-5efc-11ea-8d08-3ae93c60395f.png)

**Comment by Vlad-CSA** [comment]
All completed successfully
