### ISSUE TITLE
when you click the repeat icon the joystick is not displayed

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#92]
Description:
On the video in the icon"repeat" some black symbol appear, without explanation of its purpose
![Безымянный1](https://user-images.githubusercontent.com/63041847/79138624-801e9400-7dbd-11ea-88d8-a4642a85285d.png)

**Comment by pavladan** [comment]
Fixed in 6998312b0225b9550e62c0f33c35bd989d92710e
