### ISSUE TITLE
Signing in to the app through a Google account is not possible

### ISSUE THREAD

**Issue by AlexeyYarmolchyk** [easably/platform-player-extension#98]
1. Click on the application icon around the address bar.
2. Log in with your Google account by clicking on the icon.
![Screenshot_1](https://user-images.githubusercontent.com/63914916/79840680-e8bdd000-83be-11ea-88c6-1e747a3dbfef.png)
4. Enter or select a Google account.
5. Verify that authorization is complete.

**Comment by pavladan** [comment]
Fixed in [this](https://github.com/easably/platform-player-extension/releases/tag/0.8.81) release
